### ISSUE TITLE
error in libraryDepToApkLib: stdout: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1

### ISSUE THREAD

**Issue by pfn** [JetBrains/sbt-structure#33]
```
stdout: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
stdout: \
stdout:  ^
stdout:         at java.util.regex.Pattern.error(Pattern.java:1955)
stdout:         at java.util.regex.Pattern.compile(Pattern.java:1702)
stdout:         at java.util.regex.Pattern.<init>(Pattern.java:1351)
stdout:         at java.util.regex.Pattern.compile(Pattern.java:1028)
stdout:         at java.lang.String.split(String.java:2367)
stdout:         at java.lang.String.split(String.java:2409)
stdout:         at org.jetbrains.sbt.extractors.AndroidSdkPluginExtractor$.org$jetbrains$sbt$extractors$AndroidSdkPluginExtractor$$libraryDepToApkLib(AndroidSdkPluginExtractor.scala:98)
```

error here
```
  private def libraryDepToApkLib(lib: LibraryDependency): ApkLib = {
    // As for version 1.5.0 android-sdk-plugin uses canonical path to library as its name
    val fixedLibName = lib.getName.split(File.separator).last
    ApkLib(fixedLibName, lib.layout.base, lib.layout.manifest, lib.layout.sources, lib.layout.res, lib.layout.libs, lib.layout.gen)
  }
```

reason, windows: File.separator = \

**Comment by pfn** [comment]
the fix: use `File.separatorChar`
