### ISSUE TITLE
Project import error on IntelliJ IDEA 2016.3 Build #IU-163.7743.44, built on November 18, 2016

### ISSUE THREAD

**Issue by ceecer1** [JetBrains/sbt-structure#47]
```
[info] Set current project to server-root (in build file:/xxx/source/local-server/)
<set>:1: error: value lang is not a member of sbt.TaskKey[java.io.File]
SettingKey[java.lang.String]("sbt-structure-options") in Global := "resolveClassifiers"
                ^
[error] Type error in expression
[info] Applying State transformations org.jetbrains.sbt.CreateTasks from /Users/user/Library/Application Support/IntelliJIdea2016.3/Scala/launcher/sbt-structure-0.13.jar
[info] Reapplying settings...
Reference to undefined setting: 

  */*:sbtStructureOptions from */*:ssOptions ((org.jetbrains.sbt.CreateTasks) CreateTasks.scala:13)
 
	at sbt.Init$class.Uninitialized(Settings.scala:265)
	at sbt.Def$.Uninitialized(Def.scala:10)
	at sbt.Init$class.delegate(Settings.scala:191)
	at sbt.Def$.delegate(Def.scala:10)
	at sbt.Init$class.compiled(Settings.scala:138)
	at sbt.Def$.compiled(Def.scala:10)
	at sbt.Init$class.make(Settings.scala:144)
	at sbt.Def$.make(Def.scala:10)
	at sbt.Project$.makeSettings(Project.scala:350)
	at sbt.Load$.reapply(Load.scala:187)
	at sbt.BuiltinCommands$.reapply(Main.scala:233)
	at sbt.SessionSettings$.reapply(SessionSettings.scala:92)
	at org.jetbrains.sbt.CreateTasks$.applySettings(CreateTasks.scala:60)
	at org.jetbrains.sbt.CreateTasks$.apply(CreateTasks.scala:50)
	at org.jetbrains.sbt.CreateTasks$.apply(CreateTasks.scala:10)
	at sbt.BasicCommands$$anonfun$call$2$$anonfun$apply$9.apply(BasicCommands.scala:121)
	at sbt.BasicCommands$$anonfun$call$2$$anonfun$apply$9.apply(BasicCommands.scala:121)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
	at sbt.BasicCommands$$anonfun$call$2.apply(BasicCommands.scala:121)
	at sbt.BasicCommands$$anonfun$call$2.apply(BasicCommands.scala:115)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Reference to undefined setting: 
[error] 
[error]   */*:sbtStructureOptions from */*:ssOptions ((org.jetbrains.sbt.CreateTasks) CreateTasks.scala:13)
[error]  
[error] Use 'last' for the full log.
[error] Not a valid key: dump-structure (similar: build-structure, buildStructure)
[error] */*:dump-structure
[error]                   ^
```

**Comment by jastice** [comment]
Thanks, this is a known bug and will be fixed in the next update. See also: https://youtrack.jetbrains.com/issue/SCL-11005
